In [15]:
# código malla triangular
import numpy as np
import openmesh as om
import matplotlib.pyplot as plt

---
## Generar la malla y guardarla

In [16]:
#### Defino el tipo de Malla
mesh = om.TriMesh() # TriMesh es una funcion de OpenMesh (om)

#Al momento de crear los vertices se agrega un Arreglo  [x,y,z] (z=0 para asegurar 2D)
#a la funcion mesh.add_vertex()
# vertices de malla
vh0 = mesh.add_vertex([0, 0, 0])
vh1 = mesh.add_vertex([0, 10, 0])
vh2 = mesh.add_vertex([10, 0, 0])
vh3 = mesh.add_vertex([10, 10, 0])
vh4 = mesh.add_vertex([5, 0, 0])
vh5 = mesh.add_vertex([6, 10, 0])
vh6 = mesh.add_vertex([3, 5, 0])
vh7 = mesh.add_vertex([8, 5, 0])

#Celdas
fh0 = mesh.add_face(vh1, vh6, vh5)
fh1 = mesh.add_face(vh1, vh0, vh6)
fh2 = mesh.add_face(vh0, vh4, vh6)
fh3 = mesh.add_face(vh4, vh7, vh6)

fh4 = mesh.add_face(vh7, vh5, vh6)
fh5 = mesh.add_face(vh7, vh3, vh5)
fh6 = mesh.add_face(vh2, vh3, vh7)
fh7 = mesh.add_face(vh4, vh2, vh7)

#Generar archivo
om.write_mesh('siete_nodos.off', mesh)


* Cargar la malla [En el caso que uno quiere trabajar con otra malla.]
* Visualizar la malla


In [10]:
# mesh = om.read_trimesh('dm.off')
# mesh = om.read_trimesh('halfcircle.off')

# Comandos básicos
### Recorrer todos los nodos de la malla

In [11]:
for vh in mesh.vertices():
    #IMPRIMIR LAS COORDENADAS DE CADA VERTICE
    punto = mesh.point(vh)
    print(punto)

[0. 0. 0.]
[ 0. 10.  0.]
[10.  0.  0.]
[10. 10.  0.]
[5. 0. 0.]
[ 6. 10.  0.]
[3. 5. 0.]
[8. 5. 0.]


Recorrer todas las interfaces

In [12]:
contador = 0
for eh in mesh.edges():
    eIdx = eh.idx() # devuelve el indice global del elemento
    contador = contador + 1
    
eIdx = eIdx + 1
print(contador) # valor del total de numero de interfaces de la malla

print(len(mesh.edges()))

15
15


Recorrer varios niveles

In [13]:
for fh in mesh.faces():
    # IMPRIMIR LOS INDICES DE CADA CELDA(faces)
    index = fh.idx() # devuelve el indice de la celda
    print("Cara ", index)
    # Recorrer los vertices de cada cara y mostrar sus indices
    
    # print('\n')    
    for vh in mesh.fv(fh):
        idx = vh.idx() # devuelve indice del VERTICE
        print("\t vh.idx", idx)
        
    print('\n')
    for ffh in mesh.ff(fh):
        nCell = ffh.idx()
        print("\t ffh.idx", nCell)
        
    print('\n')
    for eh in mesh.fe(fh):
        nEdge = eh.idx()
        print('\t Lados', nEdge, ' boundary?', mesh.is_boundary(eh))
        
    print('\n')
            

Cara  0
	 vh.idx 1
	 vh.idx 6
	 vh.idx 5


	 ffh.idx 1
	 ffh.idx 4


	 Lados 2  boundary? True
	 Lados 0  boundary? False
	 Lados 1  boundary? False


Cara  1
	 vh.idx 1
	 vh.idx 0
	 vh.idx 6


	 ffh.idx 0
	 ffh.idx 2


	 Lados 0  boundary? False
	 Lados 3  boundary? True
	 Lados 4  boundary? False


Cara  2
	 vh.idx 0
	 vh.idx 4
	 vh.idx 6


	 ffh.idx 1
	 ffh.idx 3


	 Lados 4  boundary? False
	 Lados 5  boundary? True
	 Lados 6  boundary? False


Cara  3
	 vh.idx 4
	 vh.idx 7
	 vh.idx 6


	 ffh.idx 2
	 ffh.idx 7
	 ffh.idx 4


	 Lados 6  boundary? False
	 Lados 7  boundary? False
	 Lados 8  boundary? False


Cara  4
	 vh.idx 7
	 vh.idx 5
	 vh.idx 6


	 ffh.idx 3
	 ffh.idx 5
	 ffh.idx 0


	 Lados 8  boundary? False
	 Lados 9  boundary? False
	 Lados 1  boundary? False


Cara  5
	 vh.idx 7
	 vh.idx 3
	 vh.idx 5


	 ffh.idx 4
	 ffh.idx 6


	 Lados 9  boundary? False
	 Lados 10  boundary? False
	 Lados 11  boundary? True


Cara  6
	 vh.idx 2
	 vh.idx 3
	 vh.idx 7


	 ffh.idx 7
	 ffh.idx 5

calcular baricentro de cualquiera variable ubicado en los vértices

In [14]:
def bar(V):
    Vbar = []
    for fh in mesh.faces():
        vloc = []
        for vh in mesh.fv(fh):
            vloc.append(V[vh.idx()])    
        Vbar.append(sum(vloc)/3)        
    Vbar = np.array(Vbar)
    return Vbar

#################################################################
P=mesh.points()

X = P[:,0]
Y = P[:,1]

# arreglos que guarda los baricentros de la celda
# no es necesario declarar las variables, porque salen de una rutina
Xbar = bar(X)
Ybar = bar(Y)